#!/bin/bash

# Colors
bg='282a36' bgl='44475a' fg='f8f8f2'
red='ff5555' green='50fa7b' yellow='f1fa8c'
blue='8be9fd' magenta='bd93f9' cyan='8be9fd'
alpha='00000000' rosewater='f5e0dc' maroon='ff5555'
peach='ffb86c' IMAGE='$HOME/Pictures/Backgrounds/dracula-lady.png'

# CMD
swaylock -f \
	`# General` \
	--ignore-empty-password \
	--show-failed-attempts \
	--hide-keyboard-layout \
	--indicator-caps-lock \
	`# Appearance - change CC to your desired transparency` \
	`#--color ${bg}FF` \
	--image ${IMAGE} --scaling fill \
	--font 'Fira Sans Bold' --font-size 30 \
	`# Backspace Key` \
	--key-hl-color ${green} \
	--caps-lock-key-hl-color ${green} \
	--bs-hl-color ${rosewater} \
	--caps-lock-bs-hl-color ${rosewater} \
	`# Indicator` \
	--indicator-radius 180 \
	--indicator-thickness 10 \
	`# Inside Circle Colors` \
	--inside-color ${alpha} \
	--inside-clear-color ${alpha} \
	--inside-caps-lock-color ${alpha} \
	--inside-ver-color ${blue} \
	--inside-wrong-color ${red} \
	`# Layout Colors` \
	--layout-bg-color ${magenta} \
	--layout-border-color ${magenta} \
	--layout-text-color ${fg} \
	`# Line Colors` \
	--line-color ${bg} \
	--line-clear-color ${red} \
	--line-caps-lock-color ${bg} \
	--line-ver-color ${bg} \
	--line-wrong-color ${bg} \
	`# Ring Colors` \
	--ring-color ${magenta} \
	--ring-clear-color ${rosewater} \
	--ring-caps-lock-color ${peach} \
	--ring-ver-color ${blue} \
	--ring-wrong-color ${maroon} \
	`# Separator Color` \
	--separator-color ${bg} \
	`# Text Colors` \
	--text-color ${fg} \
	--text-clear-color ${rosewater} \
	--text-caps-lock-color ${peach} \
	--text-ver-color ${blue} \
	--text-wrong-color ${maroon} \
	--indicator-caps-lock
