#!/bin/sh

alpha='dd'
background='#282a36'
selection='#44475a'
comment='#6272a4'

yellow='#f1fa8c'
orange='#ffb86c'
red='#ff5555'
magenta='#ff79c6'
purple='#bd93f9'
blue='#6272a4'
cyan='#8be9fd'
green='50fa7b'

i3lock \
  --insidever-color=$background$alpha \
  --insidewrong-color=$background$alpha \
  --inside-color=$background$alpha \
  --ringver-color=$purple$alpha \
  --ringwrong-color=$red$alpha \
  --ringver-color=$purple$alpha \
  --ringwrong-color=$red$alpha \
  --ring-color=$blue$alpha \
  --line-uses-ring \
  --keyhl-color=$purple$alpha \
  --bshl-color=$orange$alpha \
  --separator-color=$background$alpha \
  --verif-color=$purple \
  --wrong-color=$red \
  --modif-color=$red \
  --layout-color=$blue \
  --date-color=$purple \
  --time-color=$purple \
  --screen 1 \
  --blur 1 \
  --clock \
  --indicator \
  --time-str="%H:%M:%S" \
  --date-str="%A %e %B %Y" \
  --verif-text="Checking..." \
  --wrong-text="Wrong pswd" \
  --noinput="No Input" \
  --lock-text="Locking..." \
  --lockfailed="Lock Failed" \
  --radius=140 \
  --ring-width=15 \
  --pass-media-keys \
  --pass-screen-keys \
  --pass-volume-keys \
  --time-font="Fira Sans" \
  --date-font="Fira Sans" \
  --layout-font="JetBrainsMono Nerd Font" \
  --verif-font="JetBrainsMono Nerd Font" \
  --wrong-font="JetBrainsMono Nerd Font" \

# These last five lines are commented because they concern the font you want to use.
# JetBrainsMono Nerd Font is the font that was used in the screenshot.
# To specify a favorite font, just uncomment the five lines and replace the parameter with the font you prefer.
