#!/bin/bash

iDIR="$HOME/.config/sway/mako/icons"

time=$(date +%H:%M:%S-%d-%m-%Y)
dir="$(xdg-user-dir PICTURES)/Screenshots"
file="Screenshot_${time}.png"

# notify and view screenshot
notify_cmd_shot="notify-send -h string:x-canonical-private-synchronous:shot-notify -u low -i ${iDIR}/picture.png"
notify_view() {
	if [[ -e "$dir/$file" ]]; then
		${notify_cmd_shot} "Screenshot Saved."
	else
		${notify_cmd_shot} "Screenshot Deleted."
	fi
}

# countdown
countdown() {
	for sec in $(seq $1 -1 1); do
		notify-send -h string:x-canonical-private-synchronous:shot-notify -t 1000 -i "$iDIR"/timer.png "Taking shot in : $sec"
		sleep 1
	done
}

# take shots
shotnow() {
	cd ${dir} && scrot - | tee "$file" | xclip
	notify_view
}

shot5() {
	countdown '5'
	sleep 1 && cd ${dir} && scrot - | tee "$file" | xclip
	notify_view
}

shot10() {
	countdown '10'
	sleep 1 && cd ${dir} && scrot - | tee "$file" | xclip
	notify_view
}

shotwin() {
	cd ${dir} && maim -s -B -b 3 -c 189,147,249 | tee "$file" | xclip
	notify_view
}

shotarea() {
	cd ${dir} && maim -s -B -b 3 -c 189,147,249 | tee "$file" | xclip
	notify_view
}

if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi

if [[ "$1" == "--now" ]]; then
	shotnow
elif [[ "$1" == "--in5" ]]; then
	shot5
elif [[ "$1" == "--in10" ]]; then
	shot10
elif [[ "$1" == "--win" ]]; then
	shotwin
elif [[ "$1" == "--area" ]]; then
	shotarea
else
	echo -e "Available Options : --now --in5 --in10 --win --area"
fi

exit 0
